#define PI 3.1415926f

#define SPEED_SCALE 2 * PI * 1 // for orbit speeds and rotation speeds
#define ROTATION_SPEED_SCALE 0.1 // for rotations to not go too fast when speed scale is raised
#define RADIUS_SCALE 0.3 // for orbits
#define MOONS_RADIUS_SCALE 25 // so when objects are scaled very large the moons do not render inside them
#define EXTRA_MOONS_RADIUS_SCALE 15 // so when planets are scaled very large the moons do not render inside them
#define MOONS_RADIUS_SCALE_DOWN 0.5 // for when orbits are too big
#define TINY_MOON_SIZE_SCALE 5 // for tiny moons so they show up when scale is low
#define SIZE_SCALE 0.00017 // for object size
#define SUN_SIZE_SCALE 0.05 // for sun to scale in a visually pleasing way
#define NUM_ASTEROIDS 300

#define SPACE_IND -1
#define CIRCLE_IND -2
#define SUN_IND -3
#define BELT_IND -4
#define COMET_IND -5

#define EARTH_IND 0
#define MOON_IND 1
#define MARS_IND 3
#define MERCURY_IND 5
#define VENUS_IND 6
#define JUPITER_IND 7
#define SATURN_IND 8
#define DEIMOS_IND 9
#define PHOBOS_IND 10
#define URANUS_IND 2
#define NEPTUNE_IND 4
#define IO_IND 11
#define EUROPA_IND 12
#define GANYMEDE_IND 13
#define CALLISTO_IND 14
#define TITAN_IND 15
#define ENCELADUS_IND 16
#define IAPETUS_IND 17

#define MAX_IND 18

// in earth days
#define MERCURY_ORBITAL_PERIOD 88
#define VENUS_ORBITAL_PERIOD 225
#define EARTH_ORBITAL_PERIOD 365
	#define MOON_ORBITAL_PERIOD 27
#define MARS_ORBITAL_PERIOD 687
	#define DEIMOS_ORBITAL_PERIOD 1.2625
	#define PHOBOS_ORBITAL_PERIOD 0.3125
#define JUPITER_ORBITAL_PERIOD 4333
	#define IO_ORBITAL_PERIOD 1.75
	#define EUROPA_ORBITAL_PERIOD 3.542
	#define GANYMEDE_ORBITAL_PERIOD 7.167
	#define CALLISTO_ORBITAL_PERIOD 16.7
#define SATURN_ORBITAL_PERIOD 10755.7
	#define TITAN_ORBITAL_PERIOD 15.94
	#define ENCELADUS_ORBITAL_PERIOD 1.375
	#define IAPETUS_ORBITAL_PERIOD 79
#define URANUS_ORBITAL_PERIOD 30687
#define NEPTUNE_ORBITAL_PERIOD 60182

#define BELT_ORBITAL_PERIOD (4.5 * 365) // +/- 1.5 * 365
#define COMET_ORBITAL_PERIOD 60

#define MERCURY_ORBITAL_SPEED SPEED_SCALE / MERCURY_ORBITAL_PERIOD
#define VENUS_ORBITAL_SPEED SPEED_SCALE / VENUS_ORBITAL_PERIOD
#define EARTH_ORBITAL_SPEED SPEED_SCALE / EARTH_ORBITAL_PERIOD
	#define MOON_ORBITAL_SPEED SPEED_SCALE / MOON_ORBITAL_PERIOD
#define MARS_ORBITAL_SPEED SPEED_SCALE / MARS_ORBITAL_PERIOD
	#define DEIMOS_ORBITAL_SPEED SPEED_SCALE / DEIMOS_ORBITAL_PERIOD
	#define PHOBOS_ORBITAL_SPEED SPEED_SCALE / PHOBOS_ORBITAL_PERIOD
#define JUPITER_ORBITAL_SPEED SPEED_SCALE / JUPITER_ORBITAL_PERIOD
	#define IO_ORBITAL_SPEED SPEED_SCALE / IO_ORBITAL_PERIOD
	#define EUROPA_ORBITAL_SPEED SPEED_SCALE / EUROPA_ORBITAL_PERIOD
	#define GANYMEDE_ORBITAL_SPEED SPEED_SCALE / GANYMEDE_ORBITAL_PERIOD
	#define CALLISTO_ORBITAL_SPEED SPEED_SCALE / CALLISTO_ORBITAL_PERIOD
#define SATURN_ORBITAL_SPEED SPEED_SCALE / SATURN_ORBITAL_PERIOD
	#define TITAN_ORBITAL_SPEED SPEED_SCALE / TITAN_ORBITAL_PERIOD
	#define ENCELADUS_ORBITAL_SPEED SPEED_SCALE / ENCELADUS_ORBITAL_PERIOD
	#define IAPETUS_ORBITAL_SPEED SPEED_SCALE / IAPETUS_ORBITAL_PERIOD
#define URANUS_ORBITAL_SPEED SPEED_SCALE / URANUS_ORBITAL_PERIOD
#define NEPTUNE_ORBITAL_SPEED SPEED_SCALE / NEPTUNE_ORBITAL_PERIOD

#define BELT_ORBITAL_SPEED SPEED_SCALE / BELT_ORBITAL_PERIOD
#define COMET_ORBITAL_SPEED SPEED_SCALE / COMET_ORBITAL_PERIOD

// in millions of miles
#define MERCURY_ORBITAL_RADIUS 36 * RADIUS_SCALE
#define VENUS_ORBITAL_RADIUS 67 * RADIUS_SCALE
#define EARTH_ORBITAL_RADIUS 93 * RADIUS_SCALE
	#define MOON_ORBITAL_RADIUS 0.239 * RADIUS_SCALE * MOONS_RADIUS_SCALE * 2
#define MARS_ORBITAL_RADIUS 142 * RADIUS_SCALE
	#define DEIMOS_ORBITAL_RADIUS 0.014573 * RADIUS_SCALE * MOONS_RADIUS_SCALE * EXTRA_MOONS_RADIUS_SCALE
	#define PHOBOS_ORBITAL_RADIUS 0.005826 * RADIUS_SCALE * MOONS_RADIUS_SCALE * EXTRA_MOONS_RADIUS_SCALE
#define JUPITER_ORBITAL_RADIUS 484 * RADIUS_SCALE
	#define IO_ORBITAL_RADIUS 0.262 * RADIUS_SCALE * MOONS_RADIUS_SCALE * EXTRA_MOONS_RADIUS_SCALE * MOONS_RADIUS_SCALE_DOWN
	#define EUROPA_ORBITAL_RADIUS 0.417 * RADIUS_SCALE * MOONS_RADIUS_SCALE * EXTRA_MOONS_RADIUS_SCALE * MOONS_RADIUS_SCALE_DOWN
	#define GANYMEDE_ORBITAL_RADIUS 0.665 * RADIUS_SCALE * MOONS_RADIUS_SCALE * EXTRA_MOONS_RADIUS_SCALE * MOONS_RADIUS_SCALE_DOWN
	#define CALLISTO_ORBITAL_RADIUS 1.168 * RADIUS_SCALE * MOONS_RADIUS_SCALE * EXTRA_MOONS_RADIUS_SCALE * MOONS_RADIUS_SCALE_DOWN
#define SATURN_ORBITAL_RADIUS 891 * RADIUS_SCALE
	#define TITAN_ORBITAL_RADIUS 0.759 * RADIUS_SCALE * MOONS_RADIUS_SCALE * EXTRA_MOONS_RADIUS_SCALE * MOONS_RADIUS_SCALE_DOWN
	#define ENCELADUS_ORBITAL_RADIUS 0.148 * RADIUS_SCALE * MOONS_RADIUS_SCALE * EXTRA_MOONS_RADIUS_SCALE  * 2 // * MOONS_RADIUS_SCALE_DOWN
	#define IAPETUS_ORBITAL_RADIUS 2.213 * RADIUS_SCALE * MOONS_RADIUS_SCALE * EXTRA_MOONS_RADIUS_SCALE * MOONS_RADIUS_SCALE_DOWN * 0.6
#define URANUS_ORBITAL_RADIUS 1784 * RADIUS_SCALE
#define NEPTUNE_ORBITAL_RADIUS 2793 * RADIUS_SCALE

#define BELT_ORBITAL_RADIUS 2.7 * EARTH_ORBITAL_RADIUS // +/- 0.5 AU
#define COMET_ORBITAL_RADIUS 2 * EARTH_ORBITAL_RADIUS

// in miles
#define SUN_RADIUS 432170 * SIZE_SCALE * SUN_SIZE_SCALE
#define MERCURY_RADIUS 1516 * SIZE_SCALE
#define VENUS_RADIUS 3760 * SIZE_SCALE
#define EARTH_RADIUS 3959 * SIZE_SCALE
	#define MOON_RADIUS 1079 * SIZE_SCALE
#define MARS_RADIUS 2106 * SIZE_SCALE
	#define DEIMOS_RADIUS 3.9 * SIZE_SCALE * TINY_MOON_SIZE_SCALE
	#define PHOBOS_RADIUS 7 * SIZE_SCALE * TINY_MOON_SIZE_SCALE
#define JUPITER_RADIUS 43441 * SIZE_SCALE
	#define IO_RADIUS 1131.9 * SIZE_SCALE
	#define EUROPA_RADIUS 969.84 * SIZE_SCALE
	#define GANYMEDE_RADIUS 1636.8 * SIZE_SCALE
	#define CALLISTO_RADIUS 1497.7 * SIZE_SCALE
#define SATURN_RADIUS 36184 * SIZE_SCALE
#define SATURN_RING_SCALE_FACTOR 1.38182622153
	#define TITAN_RADIUS 1599.9 * SIZE_SCALE
	#define ENCELADUS_RADIUS 156.65 * SIZE_SCALE
	#define IAPETUS_RADIUS 456.4 * SIZE_SCALE
#define URANUS_RADIUS 15795 * SIZE_SCALE
#define NEPTUNE_RADIUS 15299 * SIZE_SCALE

#define BELT_RADIUS 10 * SIZE_SCALE * TINY_MOON_SIZE_SCALE
#define COMET_RADIUS 19 * SIZE_SCALE * TINY_MOON_SIZE_SCALE

// day length w.r.t. earth days
#define SUN_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 25
#define MERCURY_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 59
#define VENUS_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / -243
#define EARTH_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 1
	#define MOON_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 29
#define MARS_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 1.02569
	#define DEIMOS_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 1.2625
	#define PHOBOS_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 0.3125
#define JUPITER_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 0.41358
	#define IO_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 1.75
	#define EUROPA_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 3.542
	#define GANYMEDE_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 7.167
	#define CALLISTO_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 16.7
#define SATURN_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 0.4375
	#define TITAN_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 15.94
	#define ENCELADUS_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 1.375
	#define IAPETUS_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 79
#define URANUS_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / -0.718
#define NEPTUNE_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 0.671

#define BELT_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 0.5
#define COMET_DAY ROTATION_SPEED_SCALE * SPEED_SCALE / 0.5

// axial tilt
